### ISSUE TITLE
When starting script halfway through a song, progress bar starts at 0

### ISSUE THREAD

**Issue by franc-ist** [GiovanniMCMXCIX/DiscoSpotipy#3]
![](https://cdn.discordapp.com/attachments/204174105644105728/385185283861381120/image.png)
![](https://cdn.discordapp.com/attachments/204174105644105728/385185242694025226/image.png)

**Comment by GiovanniMCMXCIX** [comment]
that's because when I made this script before the new look on canary and it showed only what time was left
I'll have a look tomorrow
